# Numpy Basics

In [66]:
import numpy as np # by convention we call it np

In [18]:
# Numpy brings some new data structures and performant routines
my_arr = np.arange(3,10) # an array-range can only contain the same data-type
my_l = list(my_arr)
my_l
my_arr

array([3, 4, 5, 6, 7, 8, 9])

In [63]:
# the arange is more performant than a list for non-trivial data sets
# Jupyter notebooks can use special syntax for immediate code  '%'
%time for i in range(1000): my_a2 = my_arr*2
%time for i in range(1000): my_l2 = [x*2 for x in my_l] # 

CPU times: total: 0 ns
Wall time: 637 µs
CPU times: total: 0 ns
Wall time: 2.02 ms


## the n-dimensional array

In [70]:
data = np.random.randn(2,3)
data
data.shape
data.dtype

dtype('float64')

In [71]:
data1 = [6,7,5,3,1]
arr1 = np.array(data1)
arr1.dtype

dtype('int32')

In [78]:
# we can populate automatically
np.zeros((3,6))
np.empty((2,3,2)) # empty will not actually be empty!

array([[[7.51803366e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.20953760e-312, 9.83920581e-072]],

       [[9.33610908e+164, 1.20885784e+161],
        [6.18632106e+169, 2.44948423e-056],
        [1.64693286e+185, 4.27480633e-033]]])

In [79]:
# data types
arr3 = arr1.astype(np.string_)
arr3

array([b'6', b'7', b'5', b'3', b'1'], dtype='|S11')

In [83]:
#Maths
arr1**arr1
arr1 >3

array([ True,  True,  True, False, False])

In [88]:
# indexing and slicing
c = np.arange(10, 0, -1)
c[2:8:2] # exactly as in Python

array([8, 6, 4])

In [93]:
# transposition
data.T

array([[ 0.32291992,  1.04093545],
       [ 0.73406577,  1.38711096],
       [ 0.55090296, -0.33715673]])

In [95]:
# statistics
np.exp(data)

array([[1.38115475, 2.08353459, 1.73481878],
       [2.83186485, 4.00326772, 0.71379696]])